### ISSUE TITLE
Popped value substitution

### ISSUE THREAD

**Issue by Jepkins** [crefr/mystack#1]
If u change last element of a stack right before popping it, no error occurs
```
    for (int32_t index = 0; index < 128; index++){
        stackPush(&mystk, index);
    }

    for (size_t index = 0; index < 96; index++){
        printf("%d\n", stackPop(&mystk));
        if (index == 65)
            memset(mystk.data + mystk.size - 1,1,1);
    }
    stackDump(&mystk);
    stackDtor(&mystk);
```
![image](https://github.com/user-attachments/assets/3566ee22-e1a7-44f9-9124-9692e35d290b)

Possible solution: check hash before popping

UPD: in fact, any memory corruption before push/pop is not traced

**Comment by crefr** [comment]
Will be fixed in the next commit
