### ISSUE TITLE
Hashing problem

### ISSUE THREAD

**Issue by Jepkins** [crefr/mystack#3]
You can swap contents of stack data and stack structure keeping stk.capacity, errNo and canaries untouched, and this will not be tracked
```
stack_t mystk = stackCtor(sizeof(mystk) / sizeof(int32_t) - 1);
int32_t* orig_data = (int32_t*)mystk.data;
for (int32_t index = 1; index < sizeof(mystk) / sizeof(index); index++){
    if (index == (int32_t)((int32_t*)&mystk.size - (int32_t*)&mystk))
    {
        stackPush(&mystk, 7);
        stackPush(&mystk, 0);
        index++;
        continue;
    }
    // if (index == (int32_t)((int32_t*)&mystk.data - (int32_t*)&mystk))
    // {
    //     stackPush(&mystk, rand());
    //     stackPush(&mystk, rand());
    //     index++;
    //     continue;
    // }

    stackPush(&mystk, *((int32_t*)&mystk + index));
}

printf("[LINE %d]: struct_hash = %X, data_hash = %X ", // ...);
printf("data = %p, hash = %X, c1 = %lX, c2 = %lX, size = %lu, cap = %lu, errno = %d\n", // ...);

for (size_t index = 1; index < sizeof(mystk) / sizeof(index); index++){
    int32_t temp = 0;
    memcpy(&temp, (int32_t*)&mystk + index, sizeof(int32_t));
    memcpy((int32_t*)&mystk + index, orig_data + index - 1, sizeof(int32_t));
    memcpy(orig_data + index - 1, &temp, sizeof(int32_t));
}

printf("[LINE %d]: struct_hash = %X, data_hash = %X ", // ...);
printf("data = %p, hash = %X, c1 = %lX, c2 = %lX, size = %lu, cap = %lu, errno = %d\n", // ...);

for (size_t index = 0; index < 6; index++){
    printf("%d\n", stackPop(&mystk));
}

logExit();
stackDtor(&mystk);
printf("end\n");
```

Example of changing size value:
![image](https://github.com/user-attachments/assets/7135f7b5-c98c-47ac-a08c-06d7988c3280)
![image](https://github.com/user-attachments/assets/9ac09389-79b6-447d-a984-6adfff6c2651)

Changing mystk.data value rezults in silent segfault:
![image](https://github.com/user-attachments/assets/49610bfc-e82d-4e47-84cd-df331c9bf112)

NOTE: This bug is extremely hard to reproduce and can only happen if `mystk.capacity == sizeof(stack_t)`. This probably won't ever happen unintentionally

Reason this happens: in formula for calculating stk.hash hashes of data and structure itself are symmetrical arguments (swapping them does not change the outcome):
`uint32_t hash = (datahash >> 1) + (structhash >> 1);`

Possible solution: change hash calculating formula

**Comment by crefr** [comment]
Fixed in latest commit
