### ISSUE TITLE
No error checking before dump

### ISSUE THREAD

**Issue by Jepkins** [crefr/mystack#4]
```
for (int32_t index = 0; index < 10; index++){
    stackPush(&mystk, index*20);
}
mystk.data = mystk.data + 5;
stackDump(&mystk);
```
Results in this:
![image](https://github.com/user-attachments/assets/1c950c63-1e00-4fba-b52b-6d9db11686ff)

Reason: there is no STACKASSERT() at the beginning of stackDump() function:
```
void stackDump(stack_t * stk)
{
    assert(stk != NULL);
    logPrint(LOG_DEBUG, "-----------STACK DUMP-----------");
    logPrint(LOG_DEBUG, "stack_t[%p]{", stk);
 // ...
}
```

Possible solution: add STACKASSERT()

**Comment by crefr** [comment]
Has fixed it in latest commit, added some checks for stack before dumping
